### ISSUE TITLE
Seemingly incorrect proxy command in the README.md

### ISSUE THREAD

**Issue by Cmoore-i2** [i2group/notebook-sdk#18] opened 2024-04-30 13:17 UTC
Whilst following the README.md instructions the command `npx @i2analyze/notebook-sdk-plugin-proxy --config devproxy.json` fails. To be more specific, the command itself doesn't fail in the terminal but at the address the terminal output gives eg `http://localhost:4000/` none of the changes are displayed there, the plugin appears to not have been loaded.

Running `npx @i2analyze/notebook-sdk-plugin-proxy@dev --config devproxy.json` instead appears to fix this issue. I'd raise a PR but it's not possible for me.

**Comment by Anthony-Johnson-i2** [comment] 2024-04-30 14:25
Hi @Cmoore-i2  Cameron

As you are internal to i2  you can also ask this sort of question on the Ask-i2 internal teams channel or you can talk to the dev team who work on this directly. (It is also useful for such observations to be seen here as well where others might benefit too :-) ) 

There is a process we have for managing internally found issues whether they are documentation problems or code issues and these alter dependant on whether we feel customers might be affected or not and whether the issue is found by a member of R&D or not.

I'll let the dev team know and they can decide whether to interact with you here or via teams etc.

Cheers

**Comment by Tim-Mawson-i2** [comment] 2024-05-01 06:36
Closing this as the issue is fixed, pending release.

**Closed as completed by Tim-Mawson-i2** 2024-05-01 06:36 UTC

**Comment by Anthony-Johnson-i2** [comment] 2024-05-01 06:37
Excellent !
Thanks @Tim-Mawson-i2
